<?php
/** @var \DaveBaker\Form\Block\Error\Main $block */
/** @var \DaveBaker\Form\Validation\Error\ErrorInterface $error  */

if(!$errors = $block->getErrors()){
    return;
}
?>
<div <?php echo $block->getAttrs();?>>
    <ul class="alert-list">
    <?php foreach($errors as $error):?>
        <li><?php echo $block->escapeHtml($error->getMainError());?></li>
    <?php endforeach; ?>
    </ul>
</div>
