<?php
/** @var \DaveBaker\Form\Block\Form $block */
// TODO: Take out temp styles
?>
<style>
    form input{
        display: block;
        clear:right;
        margin-bottom: 15px;
    }
</style>
<form 
    name="<?php echo $block->escAttr($block->getElementName());?>"
    method="<?php echo $block->escAttr($block->getFormMethod());?>"
    action="<?php echo $block->escAttr($block->getFormAction());?>"
    <?php echo $block->getAttrs();?> >
    <?php echo $block->getChildHtml(''); ?>
</form>
