<?php
/** @var \DaveBaker\Form\Block\Form $block */
?>
<style>
    form input{
        display: block;
        clear:right;
        margin-bottom: 15px;
    }
</style>
<form 
    name="<?php echo $block->escAttr($block->getElementName());?>"
    method="<?php echo $block->escAttr($block->getMethod());?>"
    action="<?php echo $block->escAttr($block->getAction());?>"
    <?php echo $block->getAttrs();?> >
    <?php echo $block->getChildHtml(''); ?>
</form>
