<?php /** @var \DaveBaker\Core\Block\Components\Paginator $block */ ?>
<ul <?php echo $block->getAttrs();?>>
    <li <?php echo $block->getPreviousButtonAttrs();?> class="page-item">
        <a href="<?php echo $block->getPreviousButtonHref();?>" class="page-link"><?php echo __("Previous");?></a></li>
        <?php for($i = 1; $i <= $this->getTotalPages(); $i++):?>
            <li <?php echo $this->getItemAttrs($i);?> class="page-item">
                <a href="<? echo $block->getItemHref($i);?>" class="page-link"><?php echo $i;?></a>
            </li>
        <?php endfor; ?>
    <li <?php echo $block->getNextButtonAttrs();?> class="page-item">
        <a href="<?php echo $block->getNextButtonHref();?>" class="page-link"><?php echo __("Next");?></a></li>
    </li>
</ul>
