<?php
/** @var \DaveBaker\Core\Block\Html\Table $block */
?>
<?php if($this->getRecords()): ?>
<table <?php echo $block->getAttrs(); ?>>

    <?php if($this->getHeaders()): ?>
        <thead>
            <tr>
                <?php foreach($block->getHeaders() as $header): ?>
                    <th><?php echo $block->escapeHtml($header); ?></th>
                <?php endforeach;?>
            </tr>
        </thead>
        <tbody>
            <?php foreach($block->getRecords() as $record): ?>
            <tr>
                <?php foreach($block->getHeaderKeys() as $k => $header): ?>
                    <td><?php echo $this->escapeHtml($record->getOutputData($header), $header); ?></td>
                <?php endforeach; ?>
            </tr>
            <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
</table>
<?php endif; ?>